### ISSUE TITLE
Issue with credentials logger

### ISSUE THREAD

**Issue by juli1** [codiga/jetbrains-plugin#151]
**Describe the bug**

There is an issue with the code that stores the user credentials. See below.

```
java.lang.Throwable: find: An invalid record was encountered. (-67701)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:184)
	at com.intellij.credentialStore.KeyChainCredentialStore$Companion.checkForError(macOsKeychainLibrary.kt:86)
	at com.intellij.credentialStore.KeyChainCredentialStore$Companion.findGenericPassword(macOsKeychainLibrary.kt:35)
	at com.intellij.credentialStore.KeyChainCredentialStore$Companion.access$findGenericPassword(macOsKeychainLibrary.kt:27)
	at com.intellij.credentialStore.KeyChainCredentialStore.get(macOsKeychainLibrary.kt:94)
	at com.intellij.credentialStore.NativeCredentialStoreWrapper.get(NativeCredentialStoreWrapper.kt:46)
	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.get(PasswordSafeImpl.kt:90)
	at io.codiga.plugins.jetbrains.settings.application.AppSettingsState.getApiToken(AppSettingsState.java:96)
	at io.codiga.plugins.jetbrains.graphql.CodigaApiImpl.getHeaders(CodigaApiImpl.java:56)
	at io.codiga.plugins.jetbrains.graphql.CodigaApiImpl.getRecipesForClientByShotcurtLastTimestmap(CodigaApiImpl.java:203)
	at io.codiga.plugins.jetbrains.cache.ShortcutCache.updateKey(ShortcutCache.java:73)
	at io.codiga.plugins.jetbrains.cache.ShortcutCache.refreshCacheKey(ShortcutCache.java:127)
	at io.codiga.plugins.jetbrains.cache.CacheRefreshEditorListener.refreshCache(CacheRefreshEditorListener.java:63)
	at io.codiga.plugins.jetbrains.cache.CacheRefreshEditorListener.lambda$runBackgroundProcess$1(CacheRefreshEditorListener.java:50)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:941)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:150)
	at io.codiga.plugins.jetbrains.cache.CacheRefreshEditorListener.runBackgroundProcess(CacheRefreshEditorListener.java:50)
	at io.codiga.plugins.jetbrains.cache.CacheRefreshEditorListener.lambda$selectionChanged$0(CacheRefreshEditorListener.java:38)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by juli1** [comment]
Discussed with @picimako about this issue. We will catch the issue and not surface a bug to the user.
